### ISSUE TITLE
Issue with Contribution receipts?

### ISSUE THREAD

**Issue by ingageco** [deboorn/FellowshipOne-API#4]
@deboorn  - Thanks for this great code. I've tried the following call:

`$r = $f1->json()->contributionreceipts()->search(array(
        "startReceivedDate" => $monthbegin,
        "endReceivedDate" => $monthend
    ))->get();`

And get the error. I've also tried: 

`$r = $f1->json()->contributionreceipts()->search(array(
        "startReceivedDate" => $monthbegin,
        "endReceivedDate" => $monthend
    ))->search();`

When I look at what's returned in debug, the api path is correct ("contributionreceipts_search{parameter}_search) but there are no pathIds. Isn't pathIds supposed to reflect the parameters that I'm calling?

I'm at a loss... any help is greatly appreciated.

**Comment by ingageco** [comment]
$monthbegin and $monthend are simple date strings: 

`$monthbegin = "2010-01-01";
    $monthend = "2014-01-31";`

**Comment by ingageco** [comment]
More debug info: 

` ["endpointId":protected]=>
  string(34) "contributionreceipts_search_search"
  ["pathIds":protected]=>
  array(0) {
  }
  ["response":protected]=>
  NULL`

**Comment by deboorn** [comment]
Thanks for the bug report. I've scheduled time tonight to have a look and report back.

**Comment by ingageco** [comment]
Thanks @deboorn

Best,

-- 
Jay Hughes

On October 1, 2015 at 9:36:46 AM, Daniel Boorn (notifications@github.com) wrote:

Thanks for the bug report. I've scheduled time tonight to have a look and report back.

**Comment by ingageco** [comment]
Also tried with an individual ID only and a production key that I'm certain has access - no success.

**Comment by deboorn** [comment]
Noticed the path url may be incorrect for that endpoint. I updated it (see commit link below). Please give it a try and let me know how it goes.

https://github.com/deboorn/FellowshipOne-API/commit/feeb135771b8880eafbdb59b9e7adf9449237382

**Comment by ingageco** [comment]
Are the parameters being added? I try the 1st call above and I'm told that I am passing no parameters. It looks like your commit removes the parameters from being passed.

**Comment by ingageco** [comment]
See my comment on your commit - I found the fix.

**Comment by deboorn** [comment]
Thanks. Please see the commit below for the update -- 
https://github.com/deboorn/FellowshipOne-API/commit/e7db4850a8cbeb5889bdc8b58b5c144789827f65
